baseURL: "https://mdmahadi-hasan.github.io/" 
title: MD MAHADI HASAN
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /papers/
          weight: 1
        - name: Data Projects
          url: /courses/
          weight: 2
        - name: Readings
          url: /readings/
          weight: 3
       
        

params:
    description: "Md Mahadi Hasan is a master's student of Applied Economics at NDSU. His research covers Applied Econometrics, Industrial organisation & environmental economics."
    author: Md Mahadi Hasan
    googleAnalyticsID: "G-QSZX1DBDCK"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: MD MAHADI HASAN
          subtitle: "Hello, and thank you for your interest! I hold a bachelor's degree in Economics and a master's degree in Agribusiness and Applied Economics. My work and research focus on Applied Econometrics, Environmental and Resource Economics, and Machine Learning."

          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: MD MAHADI HASAN
          buttons:
            - name: Research
              url: /papers/
            - name: Data Projects
              url: /courses/
            - name: Readings
              url: /readings/
         
            

    socialIcons:
        - name: Email
          url: /contact/
        - name: GitHub
          url: https://github.com/MdMahadi-hasan
       

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "MD MAHADI HASAN"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
